oslopride/oslopride.no

web/gatsby-config.js, web/package.json, web/src/blocks/hero.js, web/src/components/layout.js, web/src/components/navigation.js, yarn.lock
=> Add styling

.huskyrc, .lintstagedrc, sanity/schemas/blocks/call-to-action-minimal.js, sanity/schemas/blocks/index.js, sanity/schemas/schema.js, web/src/blocks/call-to-action-minimal.js, web/src/components/block.js
Includes:
- Title (the small title on top)
- Headline (the large text)
- Button (the cta button)
=> Call To Action Minimal component

sanity/desk-structure/previews/page-preview.js, sanity/package.json, sanity/schemas/configuration.js, sanity/schemas/front-page.js, web/src/assets/close-button.svg, web/src/assets/menu-button-purple.svg, web/src/components/layout.js, web/src/components/navigation.js, web/src/pages/index.js, web/src/templates/page-template.js
Issue: https://github.com/oslopride/oslopride.no/issues/20
- Added global header
- Added navigation
**Web**
Header:
Nav:
**Mobile**
Header:
Nav:
=> Top header and navigation

sanity/desk-structure/index.js, sanity/desk-structure/partners.js, sanity/schemas/partner.js, sanity/schemas/schema.js
=> Add schema for partners

sanity/schemas/blocks/collapsible.js, sanity/schemas/blocks/index.js, sanity/schemas/schema.js, web/src/assets/minus.svg, web/src/assets/plus.svg, web/src/blocks/collapsible.tsx, web/src/blocks/index.tsx, web/src/sanity/models.ts, web/src/types/svg.d.ts
Adds a collapsible list block.
Closes #26
=> Collapsible list block

web/src/components/header.tsx, web/src/components/header/index.tsx, web/src/components/hero.tsx
=> Bugfix verical scroll and date overflow

sanity/schemas/blocks/advertisement.js, web/src/blocks/advertisement.tsx
Related issue: #31 
Implements design of advertisement / call-to-action block.
=> #31 Style advertisement block to match design-spec

web/src/blocks/advertisement.tsx, web/src/blocks/featured-articles.tsx, web/src/blocks/partner-preview.tsx, web/src/components/sub-heading.tsx, web/src/pages/front-page.tsx, web/src/sanity/models.ts
Initial attempt at this. Could probably use some adjusting with font sizes and responsive image behavior afterwards.
Closes #35
=> Frontpage article preview

web/package.json, web/src/app.tsx, web/src/blocks/advertisement.tsx, web/src/blocks/featured-articles.tsx, web/src/blocks/partner-preview.tsx, web/src/components/header.tsx, web/src/components/link.tsx, web/src/components/loading.tsx, web/src/index.ejs, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/event-overview.tsx, web/src/pages/front-page.tsx, web/src/pages/page.tsx, web/src/pages/partner-overview.tsx, web/webpack.config.js, yarn.lock
SEO will be 100% when we change the URL to www.oslopride.no (it's due to the canonical rel tag).
We still need to do some work on article/pages, so images within the body gets alt-tags.
Resolves #86
Resolves #82
=> Put on makeup for the big show

sanity/schemas/web-configuration.js, web/src/sanity/models.ts
=> Allow external links in site navigation menu

web/src/blocks/headliners.tsx, web/src/components/link.tsx, web/src/pages/event-overview.tsx
Ensure long description-texts on events does not break layout.
=> Cut off long event descriptions

web/src/pages/event-overview.tsx
=> improve events on desktop

web/src/pages/partner-overview.tsx
=> fix: header gradient color on partner page

web/src/components/header.tsx
=> fix: link padding on mobile menu

web/src/blocks/featured-articles.tsx
=> fix: home page featured articles margin

web/src/pages/article-overview.tsx
=> fix: article overview padding on mobile

web/src/components/header.tsx
@lovise-hub is this sort of what you meant?
Fixes #157
=> add hover color and underline on active nav link

.github/workflows/pull_request.yml
Adds a check for linting (a11y) for every PR.
I skipped doing a build check, since we're using Netlify and it has its own status check on PRs where it tries to build.
Fixes #150
=> Add workflow for PRs

.github/workflows/pull_request.yml
I don't even know if this will use the Yarn cache anymore but whatever 🤷‍♀️
=> Actually for real fix Github PR action

web/src/blocks/advertisement.tsx, web/src/blocks/featured-articles.tsx, web/src/blocks/headliners.tsx, web/src/blocks/partner-preview.tsx, web/src/components/sub-heading.tsx, web/src/pages/front-page.tsx, web/src/pages/partner-overview.tsx
=> Remove subheading line

web/src/components/angled-image.tsx, web/src/components/hero.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/error.tsx, web/src/pages/event-overview.tsx, web/src/pages/front-page.tsx, web/src/pages/not-found.tsx, web/src/pages/page.tsx, web/src/pages/partner-overview.tsx, web/src/utils/index.ts
**This updates the hero component design according to specs in issue #177**
The button is disabled by default and can be enabled by adding prop _displayScrollButton_ when using the hero component on a page.
=> Update hero component design

web/src/components/header.tsx
=> Only show menu scrollbar when necessary

web/src/blocks/featured-articles.tsx
=> open "more articles" link in same window

web/src/pages/article-overview.tsx
We are currently showing 3 articles at the time. If we would have much more articles to display we would have to reconsider this solution since it won't be efficient. 
Closes #200
=> fix: update articles page design

web/src/components/hero.tsx
closes [#issue213 ](https://github.com/oslopride/oslopride.no/issues/213)
=> fix: styling in hero component on mobile

web/src/pages/event-overview.tsx
=> Add back in stream availability as filter option

web/src/components/header.tsx
=> Fix. font size in menu

sanity/schemas/simple-event.js, web/src/pages/event-overview.tsx, web/src/sanity/models.ts
Kan filtrere på ekstern event og mini pride.
=> feat: add minipride and external arenas

web/src/pages/event-overview.tsx
Temporary fix to hide events that have already ended
=> hide old events

sanity/schemas/simple-event.js, web/src/components/event-card.tsx, web/src/pages/event-overview.tsx, web/src/pages/event.tsx, web/src/sanity/models.ts
Adding new program types "workshop", "performance" and "aktivitet for barn/unge", and new accessibility categories "simultanteksting", "teleslynge" og "engelsk".
=> add new program and accessibility types

sanity/schemas/simple-event.js, web/src/components/event-card.tsx, web/src/pages/event-overview.tsx, web/src/sanity/models.ts
Adding new categories Litteratur and Kino.
=> Add new categories for 2024
