sanity/desk-structure/configuration.js, sanity/desk-structure/index.js, sanity/schemas/blocks/index.js, sanity/schemas/blocks/partner-preview.js, sanity/schemas/partner-type.js, sanity/schemas/partner.js, sanity/schemas/schema.js, web/src/blocks/index.tsx, web/src/blocks/partner-preview.tsx, web/src/components/sub-heading.tsx, web/src/pages/front-page.tsx, web/src/sanity/models.ts
Adds a partner preview block (front page partner list with images + partner "level").
I added a `Partner type` to the configuration where you can select what partner types are available, along with referencing this for each `Partner`.
I also added a Typescript model for the `Partner` document since it was missing.
Should probably be its own PR but whatever: also moved out the "sub-heading" into its own component (the heading with a pink line next to it), since I had to re-use it.
The styling is very much less than optimal and more of a quick draft right now. I'm not sure it makes much sense to spend hours on making things pixel perfect until more of the web site is fleshed out and it can be seen in a proper context.
Closes #30
=> Partner preview block

sanity/schemas/blocks/index.js, sanity/schemas/blocks/quote.js, sanity/schemas/schema.js, web/src/assets/triangles-1.svg, web/src/assets/triangles-2.svg, web/src/blocks/index.tsx, web/src/blocks/quote.tsx, web/src/sanity/models.ts
Currently in the design this block seems to be more specific to being used as a quote (by seeing the mobile version where the triangle graphics are replaced by a quotation mark at the top?), rather than as a banner.
I decided to start off with creating this as a quote block instead of a generic banner block because of this. We could make a more generic banner component with the triangles later, when it's actually used anywhere else in the design? What do you think about that approach?
Closes #29
=> Quote block

sanity/schemas/article-archive.js, sanity/schemas/types/internal-link.js, web/src/components/angled-image.tsx, web/src/components/footer/styles.ts, web/src/components/header.tsx, web/src/components/hero.tsx, web/src/components/link.tsx, web/src/index.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/front-page.tsx, web/src/pages/page.tsx
**Related issue:**
https://github.com/oslopride/oslopride.no/issues/78
**What's included:**
- Responsive fixes:
- Text inside the menu is made slightly smaller on mobile
- Padding inside menu made smaller on mobile
- Hero image made vertically responsive, text below no longer overflows when making browser smaller
- Consistency fixes:
- All main body content has a width of 90vw, centered in the middle of the page (capped at 720px)
- Accessibility fixes:
- ARIA attributes added to the menu button (aria-haspopup, aria-controls, aria-expanded)
- Autofocus on the close/open button when interacting with the menu
- Disable reading the menu items when menu is collapsed
- Documentation: https://knowbility.org/blog/2020/accessible-slide-menus/ & …
=> Design cleanup

web/package.json, web/src/components/seo.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/front-page.tsx, web/src/pages/page.tsx, yarn.lock
This adds simple open graph support to all pages. We still should add some [google specific structured data (JSON-LD)](https://developers.google.com/search/docs/guides/search-gallery) to get good google search results, but it's not that important (we didn't use it that much last year).
The only problem is the description field for articles. The Sanity `intro` field is block content, which makes it unusable for SEO purposes (google will crawl it of course, but facebook etc will not know that this is what we want to display when pages are shared). We need to either add another field, or change the intro field to be a simple string field.
Closes #84
=> add simple open graph SEO

web/src/blocks/headliners.tsx, web/src/components/header.tsx, web/src/components/hero.tsx, web/src/components/sub-heading.tsx, web/src/pages/front-page.tsx, web/src/sanity/models.ts
- Has to have at least one headliner to appear.
- Featured events are optional
Responsive, but the front-page might need another touch-up to look good on large screens now that more components have been added.
Resolves #75
=> Headliners-support for front-page

sanity/schemas/blocks/index.js, sanity/schemas/blocks/split-pane.js, sanity/schemas/schema.js, web/src/blocks/index.tsx, web/src/blocks/split-pane.tsx, web/src/sanity/models.ts
I assumed it might make sense to simply limit it to two text area blocks (left and right field), since the main purpose would be to have text columns? Otherwise maybe it should be an array of any block -- but it's probably dumb to leave it so open-ended for the user?
I didn't do any particular styling for the block for now, besides a responsive flex direction change. I figured that maybe it's worth waiting until more of the site-wide styling is implemented, so that it can share some of the regular text area styling when that is added later.
Closes #25
=> Split pane block

web/.eslintrc, web/package.json, web/src/blocks/collapsible.tsx, web/src/blocks/partner-list.tsx, web/src/components/header.tsx, web/src/components/link.tsx, web/src/components/loading.tsx, web/src/pages/error.tsx, web/src/pages/not-found.tsx, yarn.lock
Added `eslint-plugin-jsx-a11y` to the ESLint config and tried some fixes for the few first lint errors from doing so:
- Added img role and aria-label to all emojis
- Added missing img alt tags
- Disabled valid anchor rule for the `Link` component:
```tsx
if (data === undefined) {
return (
<a className={className} css={base} href="#">
{link.text}
</a>
);
}
```
I *think* in this specific case it's ok? It's just temporarily showing the link while the URL is being resolved from Sanity. Alternative is to style some text to look like a link. I'm not sure which one is better?
- Wrapped the headers for Collapsible items in a div with a button role, and added aria-expanded and aria-controls tags along with tabindex, as well as a key handler. Not 100% sure if this was the best approach?
- Moved …
=> Add a11y linting

web/src/pages/page.tsx
The issue was for adding padding to bottom of "about us" between the content and footer. This will affect every page using the "page" template. I think this is still totally ok?
Since some pages have different styling at the bottom, we can't just simply add a top-margin to the footer itself, so every layout template will have to make its own adjustments.
I only added this to the `page` template for this issue right now, as I'm not sure if the `article` template etc. should have the exact same treatment.
Fixes #158
=> add padding to bottom of page template

sanity/schemas/front-page.js, web/src/pages/front-page.tsx, web/src/sanity/models.ts
Adds an additional body block to the frontpage for text content under hero header.
Fixes #154
=> add body block to frontpage

web/src/blocks/advertisement.tsx, web/src/blocks/headliners.tsx, web/src/components/footer/styles.ts, web/src/components/header.tsx, web/src/components/link.tsx, web/src/index.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/error.tsx, web/src/pages/event-overview.tsx, web/src/pages/front-page.tsx, web/src/pages/not-found.tsx, web/src/pages/page.tsx, web/src/pages/partner-overview.tsx
Remove a lot of "hard-coded" font-sizes and line-heights. There's still tons of others around, but I think it requires a separate cleanup to de-duplicate a lot of the common superfluous styling all over.
Fixes #140
=> use global text styling

web/src/index.tsx
Do you think using these colors is clear, it seems like the purple might be a bit too dark? But maybe having the underline makes it good enough?
`#3a1b7b` and `#184FBD` for hover.
Fixes #159
=> add global default link color

web/src/components/footer/styles.ts, web/src/utils/theme.tsx
Used the lighter yellow color in the XD sketch. I think it looks better than the "normal" yellow there? I also added the same color when the link is focused as well.
e.g. `#ffecac` vs `#ffc100`
Fixes #156
=> add hover and focus color to footer links

web/src/components/header.tsx
- Adds more top "padding" for header
Was a little torn on doing it this way, but because of all the absolute positioning it seemed like the quickest fix to just adjust the `top` position of the header itself, and then the close button (since it is in its own div and the header position does not affect it). Is there some better way to do this? Probably, but I don't know how without completely rewriting the styling and I hate CSS :)
- Adds more space between header date and menu button
Fixes #152, fixes #151
=> Header styling adjustments

sanity/schemas/front-page.js, web/src/pages/front-page.tsx, web/src/sanity/models.ts
This makes the subheading able to be edited in Sanity.
Fixes #155
=> add subheading in sanity frontpage schema

web/src/components/angled-image.tsx, web/src/components/background-image.tsx, web/src/components/hero.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/error.tsx, web/src/pages/event-overview.tsx, web/src/pages/front-page.tsx, web/src/pages/not-found.tsx, web/src/pages/page.tsx, web/src/pages/partner-overview.tsx
Basically adds CSS to the already existing (currently empty) body block that'll make sure to display the text correctly. It will only display the text once the content is added through Sanity (the "body" block in "front-page" in Sanity).
Fixes issue #178 🔧 
_This PR also includes a lot of small changes to the hero component related code to clean it up and make it easier to edit in the future!_
=> Add new content block on front page

web/src/components/hero.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/pages/error.tsx, web/src/pages/event-overview.tsx, web/src/pages/front-page.tsx, web/src/pages/not-found.tsx, web/src/pages/page.tsx, web/src/pages/partner-overview.tsx
This removes fixed height from the hero component and makes it adjust automatically based on content.
I also added overflow wrapping that breaks up very long words in article titles so they don't break out of their containers. A good example is the word "kommunikasjonsrådgiver" in [this article](https://www.oslopride.no/a/kommunikasjonsradgiver) (view on a small screen 📱)
Fixes issue #191 🔨
=> Fix hero content overflow

web/src/components/hero.tsx
Reverts oslopride/oslopride.no#196
Oopsie, approved this too eagerly. It was setting 100vh on all heros. Another attempt at a quick fix did not work so I'm just reverting this for now.
=> Revert "fix: set hero min height to 100vh"

web/src/components/scroll-up-button.tsx, web/src/pages/article.tsx, web/src/sanity/index.ts, yarn.lock
Plus some small adjustments to the article page styling.
- Fetches all articles with only necessary attributes (date, title, slug)
- Checks the current article index and decides which one is the next and prev ones (if any)
- Changed hero text to be centered according to new design
- Formatted hero date (and put in a `<time>` element)
- Added scroll up button between next/prev article links (somewhat sloppy but ok)
- Also updated yarn.lock because it was being problematic for everyone.
- Fixes a small import issue elsewhere with Sanity packages
There's currently no specific mobile design for the article footer, so a best effort was made temporarily. It looks... ok but not great.
Fixes #37, fixes #197
=> Prev and next article links

web/src/components/link.tsx
This simple fix solves issue #205 by making the link buttons change colors in the same way when focused 🔍  as on mouse hover 🐭
=> Fix button focus behavior

sanity/schemas/article.js, web/src/blocks/featured-articles.tsx, web/src/pages/article-overview.tsx, web/src/pages/article.tsx, web/src/sanity/models.ts
Solves a problem where we either had to pick between using `_createdAt` or `_updatedAt` for article publishing dates. The created date would be the creation date of the initial draft (i.e. working on an article over a longer period of time would not reflect the real publishing date).
- Add a required `publishedAt` field to articles
- Fallback to `_createdAt` if publishedAt does not exist (for old articles)
- Sort by `publishedAt`, then `_createdAt`
- Use a common format with `date-fns` to get localized dates (could still use some improvements...)
Fixes #207
=> add publishedAt to articles

sanity/schemas/partner.js, web/src/blocks/partner-list.tsx, web/src/blocks/partner-preview.tsx
This adds an option for a new partner type called "allied".
The "allied" type has been added to the list of partner types in Sanity.
It also has it's own section on the partners page and in the partner preview on the front page. The section is currently hidden as there are no allied partners to display but will appear as soon as they are added inside Sanity.
Fixes issue #217 🔨
=> Add "allied" as new partner type

web/src/pages/article.tsx
Small changes to the next / previous article links at the bottom of articles to prevent overflow happening when there are long words present.
This enforces consistent width for the grid elements and adds word-breaking for words that don't fit the element's width.
Fixes #224 🔧
=> Adjust next/prev article links to prevent overflow on mobile

web/src/pages/event-overview.tsx
This reverts commit 0cf266c7ee41682c572bf60abcf8b3333a16d845.
Turns out the stream information has been added, but is not published. On behalf of @boyeborg
=> Revert "Add back in stream availability as filter option (#236)"

sanity/schemas/simple-event.js, web/src/pages/event-overview.tsx, web/src/pages/event.tsx, web/src/sanity/models.ts
Adding new venue Salt, as well as arenas Eyr, Hippokrates, Bjerget and Schjelderup. Removing Pride Square from visible filter, but keeping all deprecated venues and arenas in Sanity so as to not invalidate existing data.
=> Add new arenas and venues
